# Prepare contract/category data

Reshape CUAD's question-answer JSON into one record per contract and clause category. Each record includes whether the category is present and all annotated answer spans. Categories with a training positive rate below 10% are removed from the training split; the official test split stays complete and unchanged.

In [26]:
import json
from pathlib import Path
import pandas as pd

## Locate and load the source data

This works whether the notebook is launched from the repository root or from the `notebooks` directory.

In [27]:
candidates = [Path.cwd(), *Path.cwd().parents]
project_root = next(path for path in candidates if (path / 'data/cuad/train_separate_questions.json').exists())
data_dir = project_root / 'data' / 'cuad'

with (data_dir / 'train_separate_questions.json').open() as f:
    train = json.load(f)
with (data_dir / 'test.json').open() as f:
    test = json.load(f)

print('Project root:', project_root)
print('Train contracts:', len(train['data']))
print('Test contracts:', len(test['data']))

Project root: /Users/aidanjiang/Documents/GitHub/Accenture-1Q-contract-review-challenge
Train contracts: 408
Test contracts: 102

## Build one record per contract/category

The category is quoted in each question. Multiple QA entries may name the same category, so their answers are combined. Answer text and offsets are retained. Categories with no answers still receive a record with `present=False` and an empty answer list. The following code removes all training rows for categories whose positive rate (`present=True` contracts / training contracts) is below 10%; test rows are untouched.

In [28]:
def get_category(question):
    parts = question.split('"')
    if len(parts) < 2:
        raise ValueError(f'Could not extract category from question: {question!r}')
    return parts[1]

def transform_split(dataset, split_name):
    records = []
    for doc in dataset['data']:
        paragraph = doc['paragraphs'][0]
        grouped_answers = {}
        for qa in paragraph['qas']:
            category = get_category(qa['question'])
            answers = grouped_answers.setdefault(category, [])
            for answer in qa['answers']:
                start = answer.get('answer_start')
                answers.append({
                    'text': answer['text'],
                    'answer_start': start,
                    'answer_end': start + len(answer['text']) if start is not None else None,
                })

        for category, answers in grouped_answers.items():
            records.append({
                'split': split_name,
                'contract_id': doc['title'],
                'contract_title': doc['title'],
                'category': category,
                'present': bool(answers),
                'answers': answers,
            })
    return records

records = transform_split(train, 'train') + transform_split(test, 'test')
df = pd.DataFrame(records)
original_category_count = df['category'].nunique()

positive_rates = (df[df['split'] == 'train'].groupby('category')['present'].mean()
                  .sort_values())
cutoff = 0.10
excluded_categories = positive_rates[positive_rates < cutoff].index.tolist()
print(f'Training positive-rate cutoff: {cutoff:.0%}')
print('Excluded categories and rates:')
print((positive_rates.loc[excluded_categories] * 100).round(2).astype(str) + '%')

df = df[~((df['split'] == 'train') & df['category'].isin(excluded_categories))].copy()
df.head()

Training positive-rate cutoff: 10%
Excluded categories and rates:
category
Source Code Escrow                   2.94%
Unlimited/All-You-Can-Eat-License    3.43%
Price Restrictions                   3.68%
Affiliate License-Licensor           4.17%
Most Favored Nation                  6.13%
Third Party Beneficiary              6.37%
No-Solicit Of Customers              6.62%
Non-Disparagement                     7.6%
Joint Ip Ownership                   9.56%
Name: present, dtype: str

,split,contract_id,contract_title,category,present,answers
0,train,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,Document Name,True,"[{'text': 'DISTRIBUTOR AGREEMENT', 'answer_sta..."
1,train,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,Parties,True,"[{'text': 'Distributor', 'answer_start': 244, ..."
2,train,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,Agreement Date,True,"[{'text': '7th day of September, 1999.', 'answ..."
3,train,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,Effective Date,True,[{'text': 'Unless earlier terminated othe...
4,train,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,Expiration Date,True,[{'text': 'The term of this Agreement shall ...

## Validate the representation

Every training contract has one row per retained category, while the official test split retains all categories. The checks below also ensure there are no duplicate pairs and that presence agrees with whether answers exist.

In [29]:
expected_contracts = len(train['data']) + len(test['data'])
category_counts = df.groupby('split')['category'].nunique()
rows_per_contract = df.groupby(['split', 'contract_id']).size()

assert df[['split', 'contract_id', 'category']].duplicated().sum() == 0
assert len(rows_per_contract) == expected_contracts
assert rows_per_contract.groupby(level='split').nunique().eq(1).all()
assert (df['present'] == df['answers'].map(bool)).all()
assert category_counts['test'] == original_category_count, category_counts.to_dict()
assert category_counts['train'] == original_category_count - len(excluded_categories), category_counts.to_dict()

print('Contracts:', expected_contracts)
print('Training categories per contract:', int(rows_per_contract.xs('train', level='split').iloc[0]))
print('Test categories per contract:', int(rows_per_contract.xs('test', level='split').iloc[0]))
expected_rows = len(train['data']) * (original_category_count - len(excluded_categories)) + len(test['data']) * original_category_count
print('Rows:', len(df), '(expected', expected_rows, ')')
print('Rows by split:')
print(df.groupby('split').size())

Contracts: 510
Training categories per contract: 32
Test categories per contract: 41
Rows: 17238 (expected 17238 )
Rows by split:
split
test      4182
train    13056
dtype: int64

## Save as JSON Lines

JSONL keeps `answers` as a proper list of objects, including multiple spans and their offsets. The output is written to `data/processed/contract_categories.jsonl`.

In [30]:
output_dir = project_root / 'data' / 'processed'
output_dir.mkdir(parents=True, exist_ok=True)
output_path = output_dir / 'contract_categories.jsonl'
df.to_json(output_path, orient='records', lines=True, force_ascii=False)
print(f'Saved {len(df):,} records to {output_path}')

Saved 17,238 records to /Users/aidanjiang/Documents/GitHub/Accenture-1Q-contract-review-challenge/data/processed/contract_categories.jsonl

## Chunk each contract

Split every contract with `chunk_contract` from `src/ingest/chunker.py`, using the
strategy decided in #22: 510 tokens per chunk with 128 tokens of overlap. Each chunk
keeps its `start_char` / `end_char` position in the original contract, which #24 uses to
work out which clauses fall in which chunk. Labels are added in #24, not here.

This takes about a minute, because every chunk is re-tokenized to check its length.

In [6]:
import sys
sys.path.insert(0, str(project_root))
from src.ingest.chunker import MAX_TOKENS, OVERLAP, chunk_contract

chunk_records = []
for split_name, dataset in [('train', train), ('test', test)]:
    for doc in dataset['data']:
        for chunk in chunk_contract(doc['paragraphs'][0]['context']):
            chunk_records.append({
                'split': split_name,
                'contract_id': doc['title'],
                'chunk_id': f"{doc['title']}__{chunk['chunk_index']}",
                **chunk,
            })

chunks = pd.DataFrame(chunk_records)
print('MAX_TOKENS:', MAX_TOKENS, '| OVERLAP:', OVERLAP)
chunks.drop(columns='text').head()

[transformers] PyTorch was not found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

MAX_TOKENS: 510 | OVERLAP: 128

,split,contract_id,chunk_id,chunk_index,start_char,end_char,n_tokens
0,train,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,0,0,1820,510
1,train,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,1,1271,2689,510
2,train,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,2,2409,3454,510
3,train,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,3,3205,4223,509
4,train,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,4,3970,5017,509

## Validate the chunks

Every contract should have at least one chunk, every chunk should fit the model, and
each chunk's offsets should give back exactly its text.

In [7]:
contract_text = {doc['title']: doc['paragraphs'][0]['context'] for doc in train['data'] + test['data']}

assert chunks['chunk_id'].is_unique
assert set(chunks['contract_id']) == set(contract_text)
assert (chunks['n_tokens'] <= MAX_TOKENS).all()
assert all(contract_text[row.contract_id][row.start_char:row.end_char] == row.text
           for row in chunks.itertuples())

print('Chunks:', len(chunks))
print('Chunks by split:')
print(chunks.groupby('split').size())
print()
print('Chunks per contract:')
print(chunks.groupby('contract_id').size().describe().round(1))

Chunks: 17079
Chunks by split:
split
test      2898
train    14181
dtype: int64

Chunks per contract:
count    510.0
mean      33.5
std       37.7
min        1.0
25%       10.0
50%       21.0
75%       42.0
max      317.0
dtype: float64

## Save the chunks as Parquet

Written to `data/processed/chunks.parquet`. The file holds the full contract text, so it
is large and gitignored. Rerun this notebook to regenerate it.

In [8]:
chunks_path = output_dir / 'chunks.parquet'
chunks.to_parquet(chunks_path, index=False)
print(f'Saved {len(chunks):,} chunks to {chunks_path}')
print(f'File size: {chunks_path.stat().st_size / 1e6:.1f} MB')

Saved 17,079 chunks to C:\Accenture-1Q-contract-review-challenge\data\processed\chunks.parquet
File size: 13.1 MB